### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by ghost** [jodconverter/docker-image-jodconverter-examples#29]
Not sure but trying to run docker image on mac m1 and get the folllowing error at startup:

`Caused by: java.io.IOException: Cannot run program "/bin/sh": error=0, Failed to exec spawn helper: pid: 40, exit value: 1
        at java.base/java.lang.ProcessBuilder.start(Unknown Source) ~[na:na]
        at java.base/java.lang.ProcessBuilder.start(Unknown Source) ~[na:na]
        at java.base/java.lang.Runtime.exec(Unknown Source) ~[na:na]
        at java.base/java.lang.Runtime.exec(Unknown Source) ~[na:na]
        at org.jodconverter.local.process.AbstractProcessManager.execute(AbstractProcessManager.java:66) ~[jodconverter-local-4.4.6-SNAPSHOT.jar!/:4.4.6-SNAPSHOT]
        at org.jodconverter.local.process.UnixProcessManager.execute(UnixProcessManager.java:68) ~[jodconverter-local-4.4.6-SNAPSHOT.jar!/:4.4.6-SNAPSHOT]
        at org.jodconverter.local.process.AbstractProcessManager.findPid(AbstractProcessManager.java:125) ~[jodconverter-local-4.4.6-SNAPSHOT.jar!/:4.4.6-SNAPSHOT]
        at org.jodconverter.local.office.LocalOfficeProcessManager.checkForExistingProcess(LocalOfficeProcessManager.java:562) ~[jodconverter-local-4.4.6-SNAPSHOT.jar!/:4.4.6-SNAPSHOT]
        ... 5 common frames omitted
Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 40, exit value: 1
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method) ~[na:na]
        at java.base/java.lang.ProcessImpl.<init>(Unknown Source) ~[na:na]
        at java.base/java.lang.ProcessImpl.start(Unknown Source) ~[na:na]
        ... 13 common frames omitted
`
Running the amd64 image on mac m1. What might be the cause?

**Comment by EugenMayer** [comment]
I do not have an arm64 so i cannot potentially test this. You will need to dig yourself here and maybe use the error message and google if there is anything common. 

If you want to contribute to arm64, please feel free to provide a PR for that - should be relatively easy considering the buildx support nowdays.

**Comment by EugenMayer** [comment]
closing due to inactivity. Open the issue anytime with a PR or similar
