### ISSUE TITLE
Offer a rest only service without web-ui

### ISSUE THREAD

**Issue by EugenMayer** [jodconverter/docker-image-jodconverter-examples#3]

**Comment by EugenMayer** [comment]
Build has been done, but struggling with startup

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xmlModelPlugin': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [springfox.documentation.schema.XmlModelPlugin] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@3234e239]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:262) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1202) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:541) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.jodconverter.sample.springboot.SpringBootRestApplication.main(SpringBootRestApplication.java:41) [classes!/:na]
```

**Comment by sbraconnier** [comment]
I think it's because you are using openjdk10. See [here](https://stackoverflow.com/questions/48622921/swagger-spring-api-xmlmodelplugin-error) for an explanation.

I would have to add an explicit jaxb dependency in the sample rest api project in order to support Java 9 and above.

See [Spring-Boot-with-Java-9-and-above](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9-and-above) for more information.

**Comment by EugenMayer** [comment]
@sbraconnier just wondering why spring variant is working out of the box ?

**Comment by sbraconnier** [comment]
If you look at the stacktrace, the exception is thrown because the bean class  `springfox.documentation.schema.XmlModelPlugin` cannot be created. This class is introduced by the springfox library (which offers Swagger support, to have a UI support for our REST Api). This library is not required in the spring module.

**Comment by sbraconnier** [comment]
I'll fix the dependencies in the REST sample module and come back to you later.

**Comment by sbraconnier** [comment]
Done, could you please try again and let me know ?

**Comment by EugenMayer** [comment]
@sbraconnier great job, it works now.

     docker run --rm -p 8080:8080 eugenmayer/jodconverter:rest

Would start it for you to test against 👍 8080

Thank you for the patch - Java10 is just by far the better choice for a docker based stack if the application is resource hungry. So this is a huge improvement!
